[workspace]

members = [
    "games",
    "games/backend_interface",
    "games/backend_win",
    "steel-lib",
    "league_of_steel",
    "testlib/app",
    "testlib/ssestub",
    "testlib",
]