[package]
name = "backend"
version = "0.2.0"
authors = ["Krzysztof Grzywocz <kgrzywocz@wp.pl>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[target.'cfg(windows)'.dependencies]
libc = "0.2"
winapi = { version = "0.3", features = ["wingdi"] }
backend_interface = { path = "../interface" }
